//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WCG_FloatUIDestroyWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WCG.FloatUIDestroy), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("OnDestroyCache", OnDestroyCache);
		L.RegFunction("SetFloatPosition", SetFloatPosition);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("m_DestroyObj", get_m_DestroyObj, set_m_DestroyObj);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDestroyCache(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.FloatUIDestroy obj = (WCG.FloatUIDestroy)ToLua.CheckObject<WCG.FloatUIDestroy>(L, 1);
			obj.OnDestroyCache();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFloatPosition(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			WCG.FloatUIDestroy obj = (WCG.FloatUIDestroy)ToLua.CheckObject<WCG.FloatUIDestroy>(L, 1);
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			obj.SetFloatPosition(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_DestroyObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FloatUIDestroy obj = (WCG.FloatUIDestroy)o;
			UnityEngine.GameObject ret = obj.m_DestroyObj;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_DestroyObj on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_DestroyObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FloatUIDestroy obj = (WCG.FloatUIDestroy)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.m_DestroyObj = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_DestroyObj on a nil value");
		}
	}
}

