//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WCG_MediaMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WCG.MediaMgr), typeof(System.Object));
		L.RegFunction("PlayMusic", PlayMusic);
		L.RegFunction("SetMusicVolume", SetMusicVolume);
		L.RegFunction("GetMusicVolume", GetMusicVolume);
		L.RegFunction("SetMusicPause", SetMusicPause);
		L.RegFunction("StopMusic", StopMusic);
		L.RegFunction("ReplayMusic", ReplayMusic);
		L.RegFunction("PlaySound", PlaySound);
		L.RegFunction("SetSoundVolume", SetSoundVolume);
		L.RegFunction("GetSoundVolume", GetSoundVolume);
		L.RegFunction("SetSoundPause", SetSoundPause);
		L.RegFunction("StopSound", StopSound);
		L.RegFunction("ReplaySound", ReplaySound);
		L.RegFunction("GetClip", GetClip);
		L.RegFunction("GetClipAsync", GetClipAsync);
		L.RegFunction("PlayVideo", PlayVideo);
		L.RegFunction("New", _CreateWCG_MediaMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.RegVar("bMusicMute", get_bMusicMute, set_bMusicMute);
		L.RegVar("bSoundMute", get_bSoundMute, set_bSoundMute);
		L.RegVar("bMusicIsPlaying", get_bMusicIsPlaying, null);
		L.RegVar("bSoundIsPlaying", get_bSoundIsPlaying, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateWCG_MediaMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				WCG.MediaMgr obj = new WCG.MediaMgr();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: WCG.MediaMgr.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayMusic(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.PlayMusic(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMusicVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetMusicVolume(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMusicVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			float o = obj.GetMusicVolume();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMusicPause(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetMusicPause(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopMusic(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			obj.StopMusic();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReplayMusic(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			obj.ReplayMusic();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlaySound(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			float o = obj.PlaySound(arg0, arg1);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSoundVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetSoundVolume(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSoundVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			float o = obj.GetSoundVolume();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSoundPause(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetSoundPause(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopSound(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			obj.StopSound();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReplaySound(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			obj.ReplaySound();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetClip(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.AudioClip o = obj.GetClip(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetClipAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Events.UnityAction<UnityEngine.Object> arg1 = (UnityEngine.Events.UnityAction<UnityEngine.Object>)ToLua.CheckDelegate<UnityEngine.Events.UnityAction<UnityEngine.Object>>(L, 3);
			obj.GetClipAsync(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayVideo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			WCG.MediaMgr obj = (WCG.MediaMgr)ToLua.CheckObject<WCG.MediaMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			bool o = obj.PlayVideo(arg0, arg1, arg2);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, WCG.MediaMgr.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bMusicMute(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)o;
			bool ret = obj.bMusicMute;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bMusicMute on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bSoundMute(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)o;
			bool ret = obj.bSoundMute;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bSoundMute on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bMusicIsPlaying(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)o;
			bool ret = obj.bMusicIsPlaying;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bMusicIsPlaying on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bSoundIsPlaying(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)o;
			bool ret = obj.bSoundIsPlaying;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bSoundIsPlaying on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_bMusicMute(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.bMusicMute = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bMusicMute on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_bSoundMute(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.MediaMgr obj = (WCG.MediaMgr)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.bSoundMute = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bSoundMute on a nil value");
		}
	}
}

