//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WCG_FogForGameWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WCG.FogForGame), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("InitFogSize", InitFogSize);
		L.RegFunction("ReSetMaskTexture", ReSetMaskTexture);
		L.RegFunction("UseOldTexture", UseOldTexture);
		L.RegFunction("SaveRenderTexture", SaveRenderTexture);
		L.RegFunction("SyncFogInfo", SyncFogInfo);
		L.RegFunction("GetFogState", GetFogState);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("mRenderWidth", get_mRenderWidth, set_mRenderWidth);
		L.RegVar("mRenderHeight", get_mRenderHeight, set_mRenderHeight);
		L.RegVar("mMapWidth", get_mMapWidth, set_mMapWidth);
		L.RegVar("mMapHeigh", get_mMapHeigh, set_mMapHeigh);
		L.RegVar("mRadius", get_mRadius, set_mRadius);
		L.RegVar("mGradient", get_mGradient, set_mGradient);
		L.RegVar("mFogMaterial", get_mFogMaterial, set_mFogMaterial);
		L.RegVar("mQuadObj", get_mQuadObj, set_mQuadObj);
		L.RegVar("mFullMap", get_mFullMap, set_mFullMap);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitFogSize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WCG.FogForGame obj = (WCG.FogForGame)ToLua.CheckObject<WCG.FogForGame>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.InitFogSize(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReSetMaskTexture(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)ToLua.CheckObject<WCG.FogForGame>(L, 1);
			obj.ReSetMaskTexture();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UseOldTexture(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)ToLua.CheckObject<WCG.FogForGame>(L, 1);
			obj.UseOldTexture();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SaveRenderTexture(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)ToLua.CheckObject<WCG.FogForGame>(L, 1);
			obj.SaveRenderTexture();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SyncFogInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			WCG.FogForGame obj = (WCG.FogForGame)ToLua.CheckObject<WCG.FogForGame>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			float arg3 = (float)LuaDLL.luaL_checknumber(L, 5);
			obj.SyncFogInfo(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFogState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WCG.FogForGame obj = (WCG.FogForGame)ToLua.CheckObject<WCG.FogForGame>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			float o = obj.GetFogState(arg0, arg1);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mRenderWidth(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float ret = obj.mRenderWidth;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mRenderWidth on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mRenderHeight(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float ret = obj.mRenderHeight;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mRenderHeight on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mMapWidth(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float ret = obj.mMapWidth;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mMapWidth on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mMapHeigh(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float ret = obj.mMapHeigh;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mMapHeigh on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mRadius(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float ret = obj.mRadius;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mRadius on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mGradient(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float ret = obj.mGradient;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mGradient on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mFogMaterial(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			UnityEngine.Material ret = obj.mFogMaterial;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mFogMaterial on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mQuadObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			UnityEngine.GameObject ret = obj.mQuadObj;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mQuadObj on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mFullMap(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			UnityEngine.UI.RawImage ret = obj.mFullMap;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mFullMap on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mRenderWidth(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mRenderWidth = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mRenderWidth on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mRenderHeight(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mRenderHeight = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mRenderHeight on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mMapWidth(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mMapWidth = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mMapWidth on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mMapHeigh(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mMapHeigh = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mMapHeigh on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mRadius(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mRadius = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mRadius on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mGradient(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mGradient = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mGradient on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mFogMaterial(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.CheckObject<UnityEngine.Material>(L, 2);
			obj.mFogMaterial = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mFogMaterial on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mQuadObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.mQuadObj = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mQuadObj on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mFullMap(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.FogForGame obj = (WCG.FogForGame)o;
			UnityEngine.UI.RawImage arg0 = (UnityEngine.UI.RawImage)ToLua.CheckObject<UnityEngine.UI.RawImage>(L, 2);
			obj.mFullMap = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mFullMap on a nil value");
		}
	}
}

