//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WCG_GameMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WCG.GameMgr), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetParentByRoot", SetParentByRoot);
		L.RegFunction("InitSDKEntry", InitSDKEntry);
		L.RegFunction("GetChannel", GetChannel);
		L.RegFunction("GetChanTag", GetChanTag);
		L.RegFunction("GetGameVersion", GetGameVersion);
		L.RegFunction("SetShowFPS", SetShowFPS);
		L.RegFunction("SetFrameRate", SetFrameRate);
		L.RegFunction("InitLuaCallBackFunc", InitLuaCallBackFunc);
		L.RegFunction("SetLocalVal", SetLocalVal);
		L.RegFunction("GetLocalVal", GetLocalVal);
		L.RegFunction("IsIPhone", IsIPhone);
		L.RegFunction("IsWin", IsWin);
		L.RegFunction("IsAndroid", IsAndroid);
		L.RegFunction("Exit", Exit);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, set_Instance);
		L.RegVar("ms_luaMgr", get_ms_luaMgr, set_ms_luaMgr);
		L.RegVar("ms_sceneMgr", get_ms_sceneMgr, set_ms_sceneMgr);
		L.RegVar("ms_resourceMgr", get_ms_resourceMgr, set_ms_resourceMgr);
		L.RegVar("ms_uiMgr", get_ms_uiMgr, set_ms_uiMgr);
		L.RegVar("m_eRunMode", get_m_eRunMode, null);
		L.RegVar("m_HighlightShader", get_m_HighlightShader, set_m_HighlightShader);
		L.RegVar("m_OutlineShader", get_m_OutlineShader, set_m_OutlineShader);
		L.RegVar("m_CharacterOutLightShader", get_m_CharacterOutLightShader, set_m_CharacterOutLightShader);
		L.RegVar("m_TrasparentHighlightShader", get_m_TrasparentHighlightShader, set_m_TrasparentHighlightShader);
		L.RegVar("m_FadeoutShader", get_m_FadeoutShader, set_m_FadeoutShader);
		L.RegVar("m_FossilisedShader", get_m_FossilisedShader, set_m_FossilisedShader);
		L.RegVar("m_FossilisedMap", get_m_FossilisedMap, set_m_FossilisedMap);
		L.RegVar("m_DissolveTexture", get_m_DissolveTexture, set_m_DissolveTexture);
		L.RegVar("m_TintColorShader", get_m_TintColorShader, set_m_TintColorShader);
		L.RegVar("m_DissolveShader", get_m_DissolveShader, set_m_DissolveShader);
		L.RegVar("m_CharacterHighlightShader", get_m_CharacterHighlightShader, set_m_CharacterHighlightShader);
		L.RegVar("m_FrozenShader", get_m_FrozenShader, set_m_FrozenShader);
		L.RegVar("m_FrozenTexture", get_m_FrozenTexture, set_m_FrozenTexture);
		L.RegVar("m_UICDMaskMaterial", get_m_UICDMaskMaterial, set_m_UICDMaskMaterial);
		L.RegVar("afterImageEffect", get_afterImageEffect, set_afterImageEffect);
		L.RegVar("afterImageWithScaleEffect", get_afterImageWithScaleEffect, set_afterImageWithScaleEffect);
		L.RegVar("m_ColorOffMat", get_m_ColorOffMat, set_m_ColorOffMat);
		L.RegVar("m_SceneShader", get_m_SceneShader, set_m_SceneShader);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetParentByRoot(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			bool o = obj.SetParentByRoot(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitSDKEntry(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			obj.InitSDKEntry();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetChannel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			int o = obj.GetChannel();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetChanTag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			int o = obj.GetChanTag();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGameVersion(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			string o = obj.GetGameVersion();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetShowFPS(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetShowFPS(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFrameRate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetFrameRate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitLuaCallBackFunc(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			obj.InitLuaCallBackFunc();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLocalVal(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.SetLocalVal(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLocalVal(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.GetLocalVal(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsIPhone(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = WCG.GameMgr.IsIPhone();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsWin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = WCG.GameMgr.IsWin();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsAndroid(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = WCG.GameMgr.IsAndroid();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Exit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 1);
			obj.Exit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, WCG.GameMgr.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ms_luaMgr(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, WCG.GameMgr.ms_luaMgr);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ms_sceneMgr(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, WCG.GameMgr.ms_sceneMgr);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ms_resourceMgr(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, WCG.GameMgr.ms_resourceMgr);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ms_uiMgr(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, WCG.GameMgr.ms_uiMgr);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_eRunMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			WCG.RunMode ret = obj.m_eRunMode;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_eRunMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_HighlightShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_HighlightShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_HighlightShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_OutlineShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_OutlineShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_OutlineShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_CharacterOutLightShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_CharacterOutLightShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_CharacterOutLightShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_TrasparentHighlightShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_TrasparentHighlightShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_TrasparentHighlightShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_FadeoutShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_FadeoutShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_FadeoutShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_FossilisedShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_FossilisedShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_FossilisedShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_FossilisedMap(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Texture ret = obj.m_FossilisedMap;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_FossilisedMap on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_DissolveTexture(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Texture ret = obj.m_DissolveTexture;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_DissolveTexture on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_TintColorShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_TintColorShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_TintColorShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_DissolveShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_DissolveShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_DissolveShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_CharacterHighlightShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_CharacterHighlightShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_CharacterHighlightShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_FrozenShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_FrozenShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_FrozenShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_FrozenTexture(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Texture ret = obj.m_FrozenTexture;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_FrozenTexture on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_UICDMaskMaterial(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Material ret = obj.m_UICDMaskMaterial;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_UICDMaskMaterial on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_afterImageEffect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			WCG.AfterImageEffect ret = obj.afterImageEffect;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index afterImageEffect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_afterImageWithScaleEffect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			WCG.AfterImageWithScaleEffect ret = obj.afterImageWithScaleEffect;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index afterImageWithScaleEffect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_ColorOffMat(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Material ret = obj.m_ColorOffMat;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_ColorOffMat on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_SceneShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader ret = obj.m_SceneShader;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_SceneShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Instance(IntPtr L)
	{
		try
		{
			WCG.GameMgr arg0 = (WCG.GameMgr)ToLua.CheckObject<WCG.GameMgr>(L, 2);
			WCG.GameMgr.Instance = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ms_luaMgr(IntPtr L)
	{
		try
		{
			LuaScriptMgr arg0 = (LuaScriptMgr)ToLua.CheckObject<LuaScriptMgr>(L, 2);
			WCG.GameMgr.ms_luaMgr = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ms_sceneMgr(IntPtr L)
	{
		try
		{
			WCG.SceneMgr arg0 = (WCG.SceneMgr)ToLua.CheckObject<WCG.SceneMgr>(L, 2);
			WCG.GameMgr.ms_sceneMgr = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ms_resourceMgr(IntPtr L)
	{
		try
		{
			WCG.ResourceMgr arg0 = (WCG.ResourceMgr)ToLua.CheckObject<WCG.ResourceMgr>(L, 2);
			WCG.GameMgr.ms_resourceMgr = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ms_uiMgr(IntPtr L)
	{
		try
		{
			WCG.UIMgr arg0 = (WCG.UIMgr)ToLua.CheckObject<WCG.UIMgr>(L, 2);
			WCG.GameMgr.ms_uiMgr = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_HighlightShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_HighlightShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_HighlightShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_OutlineShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_OutlineShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_OutlineShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_CharacterOutLightShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_CharacterOutLightShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_CharacterOutLightShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_TrasparentHighlightShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_TrasparentHighlightShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_TrasparentHighlightShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_FadeoutShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_FadeoutShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_FadeoutShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_FossilisedShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_FossilisedShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_FossilisedShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_FossilisedMap(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Texture arg0 = (UnityEngine.Texture)ToLua.CheckObject<UnityEngine.Texture>(L, 2);
			obj.m_FossilisedMap = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_FossilisedMap on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_DissolveTexture(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Texture arg0 = (UnityEngine.Texture)ToLua.CheckObject<UnityEngine.Texture>(L, 2);
			obj.m_DissolveTexture = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_DissolveTexture on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_TintColorShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_TintColorShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_TintColorShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_DissolveShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_DissolveShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_DissolveShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_CharacterHighlightShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_CharacterHighlightShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_CharacterHighlightShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_FrozenShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_FrozenShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_FrozenShader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_FrozenTexture(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Texture arg0 = (UnityEngine.Texture)ToLua.CheckObject<UnityEngine.Texture>(L, 2);
			obj.m_FrozenTexture = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_FrozenTexture on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_UICDMaskMaterial(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.CheckObject<UnityEngine.Material>(L, 2);
			obj.m_UICDMaskMaterial = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_UICDMaskMaterial on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_afterImageEffect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			WCG.AfterImageEffect arg0 = (WCG.AfterImageEffect)ToLua.CheckObject<WCG.AfterImageEffect>(L, 2);
			obj.afterImageEffect = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index afterImageEffect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_afterImageWithScaleEffect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			WCG.AfterImageWithScaleEffect arg0 = (WCG.AfterImageWithScaleEffect)ToLua.CheckObject<WCG.AfterImageWithScaleEffect>(L, 2);
			obj.afterImageWithScaleEffect = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index afterImageWithScaleEffect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_ColorOffMat(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.CheckObject<UnityEngine.Material>(L, 2);
			obj.m_ColorOffMat = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_ColorOffMat on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_SceneShader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WCG.GameMgr obj = (WCG.GameMgr)o;
			UnityEngine.Shader arg0 = (UnityEngine.Shader)ToLua.CheckObject(L, 2, typeof(UnityEngine.Shader));
			obj.m_SceneShader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_SceneShader on a nil value");
		}
	}
}

